apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "xray.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "xray.name" . }}
    chart: {{ template "xray.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.json: |-
{{- if .Values.configmap }}
{{- tpl .Values.configmap . | nindent 4 }}
{{- end }}